### ISSUE TITLE
Consider adding verification procedures

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/eat#18] opened 2019-07-19 19:39 UTC
Guidance on verification procedures not covered in document.  It is touched upon in Sec. 1.3, but not to the level described in comparable specifications (see https://www.w3.org/TR/webauthn/#defined-attestation-formats).

**Comment by nedmsmith** [comment] 2019-07-22 19:02
The architecture draft should define the scope of verification semantics in terms of 'duties' and if it is appropriate for the Attester to be allowed to specify 'verification procedures' that the Verifier should follow. Verifiers are presumed to be authoritative entities regarding evaluation of evidence. It isn't clear if there is a goal to define interoperability between multiple verifier entities (something that isn't currently anticipated by the architecture IMO.)

**Comment by laurencelundblade** [comment] 2019-07-23 15:49
EAT inherits verification procedures from JWT and CWT so no need for it in the EAT document. 

We could add some things over and above CWT and JWT, but I don't see anything obvious.

Stuff could also go in the architecture document or in individual profile documents.

**Comment by gmandyam** [comment] 2019-07-23 16:37
@laurencelundblade @nedmsmith 

I had some motivations for raising this issue:

a) To improve readability of the document by grouping all verification guidance into one section.  This would apply even if we think the guidance can be limited to "Use COSE verification procedures" and/or "the verifier can ignore claims that it has no interest in or cannot interpret" (as crude examples).

b) Since EAT is a CWT (or JWT - still to be confirmed by group), it inherits the claim set from CWT.  There are some claims in CWT whose relationship to EAT claims is not obvious and could be subject to varying interpretations.  Some examples:
    i. aud claim.  If present, does the verifier have to have a relationship with the entity identified by 'aud'?    Should the token be rejected if the verifier does not recognize 'aud'?
   ii. iat and age/uptime claims.  Should the verifier treat iat independently of age/uptime, or can the verifier cast them to a common timeline?  This may affect how the verifier assesses the claims in the context of security (e.g. stale location state with respect to when the token was created).

We don't need to be prescriptive, but we can provide general guidance in the processing of claims.

c) Verification of nested EATs and aggregated EATs.  If different verifiers are employed for different EAT's in a nested or aggregated structure, how do the verifiers interoperate?  Note that this may be better handled in the architecture doc, but the -01 version of the document treats the verifier as a monolith.  I believe this is also the nature the comment by @nedmsmith above.

**Comment by laurencelundblade** [comment] 2019-07-23 18:07
Saying this in a different way -- EAT inherits verification from CWT (and JWT). It would only not inherit if we explicitly said so. I don't think we should do that.

Note that the verification text in CWT and JWT result in a valid map payload. It doesn't go into anything about the claims details at all.

It seems we have an overload on the word "verify" in that some of the larger RATS architecture docs use the term for checking that the claims have acceptable values. 
This is different from the verification in CWT and JWT. 

So net-net, I don't think the EAT draft should discuss either forms of verification.

I think the issue of claims meaning being different in the EAT context is an issue and you should file a separate GitHub issue for it.

**Comment by nedmsmith** [comment] 2019-07-24 14:14
+1 on a) and b)

Regarding c) the TEEP WG observed yesterday that there can be multiple TEEs in a platform/device each having the ability to attest to something. That implies there will be different keys used to attest to claims (assertions) that are specific to the respective TEE. It was also observed that there will be a mix of vendor specific and vendor independent claims that could be asserted. I expect there will be vendor specific opaque values that only a vendor-specific verifier will be able to crack. All of the above needs to be conveyed by the attestation mechanisms. Verifiers will need to be able to navigate the complexity somehow.

On 7/23/19, 12:37 PM, "gmandyam" <notifications@github.com<mailto:notifications@github.com>> wrote:


@laurencelundblade<https://github.com/laurencelundblade> @nedmsmith<https://github.com/nedmsmith>

I had some motivations for raising this issue:

a) To improve readability of the document by grouping all verification guidance into one section. This would apply even if we think the guidance can be limited to "Use COSE verification procedures" and/or "the verifier can ignore claims that it has no interest in or cannot interpret" (as crude examples).

b) Since EAT is a CWT (or JWT - still to be confirmed by group), it inherits the claim set from CWT. There are some claims in CWT whose relationship to EAT claims is not obvious and could be subject to varying interpretations. Some examples:
i. aud claim. If present, does the verifier have to have a relationship with the entity identified by 'aud'? Should the token be rejected if the verifier does not recognize 'aud'?
ii. iat and age/uptime claims. Should the verifier treat iat independently of age/uptime, or can the verifier cast them to a common timeline? This may affect how the verifier assesses the claims in the context of security (e.g. stale location state with respect to when the token was created).

We don't need to be prescriptive, but we can provide general guidance in the processing of claims.

c) Verification of nested EATs and aggregated EATs. If different verifiers are employed for different EAT's in a nested or aggregated structure, how do the verifiers interoperate? Note that this may be better handled in the architecture doc, but the -01 version of the document treats the verifier as a monolith. I believe this is also the nature the comment by @nedmsmith<https://github.com/nedmsmith> above.

**Comment by gmandyam** [comment] 2019-08-08 00:39
Depending on the disposition of https://github.com/ietf-rats-wg/eat/issues/27, this issue may become moot.  If the operating models section is removed, then the role of verification doesn't need to be discussed anywhere else in the document.

**Comment by laurencelundblade** [comment] 2019-10-04 16:24
Can be closed because CWT and JWT cover this. Any additional coverage will go in the architecture or other documents.

**Comment by gmandyam** [comment] 2019-10-04 16:43
Closing it.

**Comment by gmandyam** [comment] 2019-10-04 16:52
I agree that any residual verification procedures (i.e. those that are not already covered in RFC 8392 and RFC 7519) could go into an architecture doc.  The current architecture doc (-02 of https://datatracker.ietf.org/doc/draft-birkholz-rats-architecture/) does not have such a section yet, however.

**Comment by laurencelundblade** [comment] 2021-08-23 20:31
Closing again. Not sure why it is still open.

To reiterate, the signature verification parts are covered by CWT and JWT. The evidence verification is covered by discussion of appraisal in the architecture document.

**Closed by laurencelundblade** 2021-08-23 20:31 UTC
Labels: ready to close
